const ENDPOINT='https://openrouter.ai/api/v1/chat/completions';
export const FIXED_MODEL='poolside/laguna-xs-2.1:free';
const ALLOWED_TYPES=new Set(['comprehensive','security','bugs','performance','quality','readability']);
export function cors(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','POST,GET,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS'){res.status(204).end();return true}return false}
export function cleanInput(body={}){const code=typeof body.code==='string'?body.code:'';if(!code.trim())throw new Error('لم يتم إرسال كود');if(code.length>900000)throw new Error('حجم الكود أكبر من الحد المسموح');return{code,fileName:String(body.fileName||'source.txt').slice(0,120),language:String(body.language||'auto').slice(0,40),reviewType:ALLOWED_TYPES.has(body.reviewType)?body.reviewType:'comprehensive',model:FIXED_MODEL}}
export async function ask({model,system,user,schema,maxTokens=12000}){const key=process.env.OPENROUTER_API_KEY;if(!key)throw new Error('متغير OPENROUTER_API_KEY غير موجود في Vercel');const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),270000);try{const schemaHint=schema?.value?`\n\nReturn ONLY one valid JSON object matching this JSON Schema exactly:\n${JSON.stringify(schema.value)}`:'';const body={model:FIXED_MODEL,temperature:.1,max_tokens:maxTokens,stream:false,messages:[{role:'system',content:system+schemaHint},{role:'user',content:user}]};const r=await fetch(ENDPOINT,{method:'POST',signal:ctrl.signal,headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','HTTP-Referer':process.env.SITE_URL||'https://code-sentinel.vercel.app','X-OpenRouter-Title':'Code Sentinel'},body:JSON.stringify(body)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error(`وصل رد غير قابل للقراءة من OpenRouter (HTTP ${r.status})`)}if(!r.ok){const msg=data?.error?.message||data?.message||`OpenRouter error ${r.status}`;const code=data?.error?.code?` [${data.error.code}]`:'';throw new Error(msg+code)}const content=data?.choices?.[0]?.message?.content;if(!content)throw new Error('قبل OpenRouter الطلب لكن الموديل لم يُرجع محتوى');return parseJSON(content)}catch(e){if(e.name==='AbortError')throw new Error('انتهت مهلة الطلب بعد 4 دقائق ونصف قبل اكتمال رد الموديل المجاني. جرّب كودًا أصغر.');throw e}finally{clearTimeout(timer)}}
function parseJSON(s){if(typeof s==='object')return s;const t=String(s).trim().replace(/^```(?:json)?/i,'').replace(/```$/,'').trim();try{return JSON.parse(t)}catch{const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a)return JSON.parse(t.slice(a,b+1));throw new Error('رد الموديل ليس JSON صالحًا')}}
export function sendError(res,e){console.error(e);res.status(/لم يتم|حجم/.test(e.message)?400:500).json({error:e.message||'خطأ داخلي'})}
export const reportSchema={name:'code_review',value:{type:'object',additionalProperties:false,required:['scores','summary','findings'],properties:{scores:{type:'object',additionalProperties:false,required:['security','performance','quality','maintainability'],properties:{security:{type:'number'},performance:{type:'number'},quality:{type:'number'},maintainability:{type:'number'}}},summary:{type:'string'},findings:{type:'array',items:{type:'object',additionalProperties:false,required:['id','type','severity','confidence','title','location','line_start','line_end','evidence','impact','fix','patch'],properties:{id:{type:'string'},type:{type:'string',enum:['security','bug','performance','quality']},severity:{type:'string',enum:['critical','high','medium','low']},confidence:{type:'string',enum:['high','medium','low']},title:{type:'string'},location:{type:'string'},line_start:{type:'integer'},line_end:{type:'integer'},evidence:{type:'string'},impact:{type:'string'},fix:{type:'string'},patch:{type:'string'}}}}}}};
export const repairSchema={name:'code_repair',value:{type:'object',additionalProperties:false,required:['fixed_code','changes','notes','verification'],properties:{fixed_code:{type:'string'},changes:{type:'array',items:{type:'string'}},notes:{type:'string'},verification:{type:'object',additionalProperties:false,required:['passed','summary','checks'],properties:{passed:{type:'boolean'},summary:{type:'string'},checks:{type:'array',items:{type:'string'}}}}}}};
export function staticVerify(original,fixed){const checks=[];let passed=true;if(!fixed||fixed.length<20){passed=false;checks.push('الكود المصحح فارغ أو قصير جدًا')}if(/\.\.\.|remaining code|rest of code|باقي الكود/i.test(fixed)){passed=false;checks.push('تم اكتشاف اختصار أو placeholder داخل الكود')}const pairs=[['{','}'],['[',']'],['(',')']];for(const[p,q]of pairs){const a=(fixed.match(new RegExp('\\'+p,'g'))||[]).length,b=(fixed.match(new RegExp('\\'+q,'g'))||[]).length;if(a!==b){passed=false;checks.push(`عدد ${p} لا يساوي عدد ${q}`)}}if(/<html/i.test(original)&&!/\<\/html\>/i.test(fixed)){passed=false;checks.push('وسم HTML الختامي مفقود')}if(passed)checks.push('لم يتم اكتشاف بتر واضح أو عدم توازن بسيط في الأقواس');return{passed,summary:passed?'اجتاز الكود فحص اكتمال بنيوي مبدئي. يلزم تشغيل الاختبارات الفعلية.':'اكتشف الفحص البنيوي ملاحظات تحتاج مراجعة.',checks}}
